return function(test, eq, contains, fixture, comment)
  test("filename search empty query keeps all files without rescanning", function()
    local f = fixture({ "a.lua", "dir/b.txt" })
    f:key("/")
    f:key("<Left>")
    f:check(function()
      contains(f:text("Files"), "a.lua")
      contains(f:text("Files"), "b.txt")
      eq(f.jobs, 3)
    end)
    f:key("<CR>")
    f:key("G")
    f:key("k")
    f:check(function()
      eq(f.jobs, 3)
    end)
    f:key("q")
    f:run()
  end)

  for _, query in ipairs({ "pha", "ALPHA" }) do
    test("full path substring search " .. query, function()
      local f = fixture(
        { "alpha/no.txt", "src/deep/Alpha.lua", "z.txt" },
        { ["src/deep/Alpha.lua"] = "matched source" }
      )
      f:key("/")
      f:paste(query)
      f:check(function()
        contains(f:text("Files"), "src/deep")
        contains(f:text("Files"), "Alpha.lua")
        contains(f:text("Files"), "no.txt")
        eq(f:win("Files").cursor, 2)
        assert(not f:text("Files"):find("z.txt", 1, true))
        contains(f:text("Source"), "no.txt")
        eq(f.jobs, 3)
      end)
      f:key("<CR>")
      f:key("q")
      f:run()
    end)
  end

  for _, query in ipairs({ "codecomment", "CODE/COMM", "cdcmnt" }) do
    test("ordered full path matching " .. query, function()
      local f = fixture({ "code/comments.lua", "other.lua" })
      f:key("/")
      f:paste(query)
      f:check(function()
        contains(f:at("Files"), "comments.lua")
        contains(f:text("Source"), "comments.lua")
        assert(not f:text("Files"):find("other.lua", 1, true))
      end)
      f:key("<CR>")
      f:key("q")
      f:run()
    end)
  end

  for _, query in ipairs({ "commnet", "é", "界é" }) do
    test("search rejects typos and split Unicode characters " .. query, function()
      local f = fixture({ "code/comments.lua", "Ã/©.lua", "é/界.lua" })
      f:key("/")
      f:paste(query)
      f:check(function()
        if query == "é" then
          contains(f:text("Files"), "界.lua")
          assert(not f:text("Files"):find("©.lua", 1, true))
        else
          eq(f:text("Files"), "No files")
        end
      end)
      f:key("<CR>")
      f:key("q")
      f:run()
    end)
  end

  test("Unicode subsequences preserve tree order rather than ranking", function()
    local f = fixture({ "aé/界.lua", "é界.lua" })
    f:key("/")
    f:paste("é界")
    f:check(function()
      contains(f:at("Files"), "界.lua")
      contains(f:text("Files"), "é界.lua")
    end)
    f:key("<CR>")
    f:key("q")
    f:run()
  end)

  test("active search navigation previews without filtering or editing query", function()
    local f = fixture({ "a.lua", "b.lua", "c.lua" }, { ["a.lua"] = "aye", ["b.lua"] = "bee", ["c.lua"] = "see" })
    f:key("j")
    f:key("/")
    f:paste(".lua")
    local builds
    f:check(function()
      contains(f:at("Files"), "b.lua")
      builds = f.tree_builds
    end)
    for _, step in ipairs({
      { "<Down>", "c.lua", "see" },
      { "<Up>", "b.lua", "bee" },
      { "<PageUp>", "a.lua", "aye" },
      { "<PageDown>", "c.lua", "see" },
      { "<Home>", "c.lua", "see" },
      { "<Right>", "c.lua", "see" },
      { "<Left>", "c.lua", "see" },
      { "<End>", "c.lua", "see" },
    }) do
      f:key(step[1])
      f:check(function()
        contains(f:at("Files"), step[2])
        contains(f:text("Source"), step[3])
        eq(f.tree_builds, builds)
        eq(f.jobs, 3)
      end)
    end
    f:key("<CR>")
    f:key("/")
    f:key("<Home>")
    f:key("b")
    f:check(function()
      contains(f:at("Files"), "b.lua")
      assert(not f:text("Files"):find("c.lua", 1, true))
    end)
    f:key("<Esc>")
    f:key("q")
    f:run()
  end)

  for _, query in ipairs({ ".", "[", "*", "%" }) do
    test("filename search treats " .. query .. " literally", function()
      local name = "special" .. query .. "name"
      local f = fixture({ "ordinary", name })
      f:key("/")
      f:paste(query)
      f:check(function()
        contains(f:text("Files"), name)
        assert(not f:text("Files"):find("ordinary", 1, true))
      end)
      f:key("<CR>")
      f:key("q")
      f:run()
    end)
  end

  for _, exit in ipairs({ "<Esc>", "<C-c>" }) do
    test("search no matches clears stale preview and " .. exit .. " restores", function()
      local f = fixture({ "a.lua", "b.lua" })
      f:key("G")
      f:key("/")
      f:paste("missing")
      f:check(function()
        eq(f:text("Files"), "No files")
        contains(f:text("Source"), "Select a file")
        eq(f:win("Files").cursor, 1)
      end)
      f:key(exit)
      f:check(function()
        contains(f:text("Files"), "a.lua")
        contains(f:text("Files"), "b.lua")
        contains(f:text("Source"), "a.lua")
        eq(f.jobs, 3)
      end)
      f:key("q")
      f:run()
    end)
  end

  test("search typing owns shortcuts, backspace and cursor movement", function()
    local f = fixture({ "jkrs123.lua", "jkrs12other.lua", "other.lua" })
    f:key("/")
    for key in ("jkrs123"):gmatch(".") do
      f:key(key)
    end
    f:key("<BS>")
    local builds
    f:check(function()
      builds = f.tree_builds
    end)
    f:key("<Left>")
    f:key("<Right>")
    f:check(function()
      eq(f.tree_builds, builds)
      contains(f:text("Files"), "jkrs12other.lua")
      contains(f:text("Files"), "jkrs123.lua")
      eq(f.jobs, 3)
      eq(f:win("Source").cursor, 2)
    end)
    f:key("<CR>")
    f:key("/")
    f:key("3")
    f:key("<CR>")
    f:check(function()
      contains(f:text("Files"), "jkrs123.lua")
      assert(not f:text("Files"):find("jkrs12other.lua", 1, true))
    end)
    f:key("<Esc>")
    f:check(function()
      contains(f:text("Files"), "other.lua")
    end)
    f:key("<Esc>")
    f:run()
  end)

  test("retained filter navigation, preview, Enter, edit and comment counts use real paths", function()
    local f = fixture({ "a.txt", "b.lua", "c.lua" }, { ["b.lua"] = "bee", ["c.lua"] = "see" })
    f:key("j")
    f:key("<CR>")
    comment(f, "on bee")
    f:key("1")
    f:key("/")
    f:paste(".lua")
    f:key("<CR>")
    f:check(function()
      contains(f:at("Files"), "b.lua ●1")
      contains(f:text("Source"), "bee")
    end)
    f:key("j")
    f:check(function()
      contains(f:at("Files"), "c.lua")
      contains(f:text("Source"), "see")
      eq(f.jobs, 3)
    end)
    f:key("e")
    f:check(function()
      eq(f.editor_paths[1], "/project/c.lua")
      contains(f:at("Files"), "c.lua")
    end)
    f:key("k")
    f:key("<CR>")
    f:check(function()
      contains(f:text("Source"), "b.lua")
      contains(f:at("Source"), "bee")
    end)
    f:key("q")
    f:run()
  end)

  test("search clamps selection and sanitizes pasted query to one line", function()
    local f = fixture({ "a.txt", "b.txt", "one two.lua" })
    f:key("G")
    f:key("/")
    f:paste("one\r\n\ttwo")
    f:check(function()
      eq(f:win("Files").cursor, 1)
      contains(f:at("Files"), "one two.lua")
    end)
    f:key("<CR>")
    f:key("q")
    f:run()
  end)

  for _, toggle in ipairs({ "h", "<Left>", "<CR>", "l", "<Right>" }) do
    test("search expands saved folds and disables " .. toggle, function()
      local f = fixture({ "src/a.txt", "src/deep/b.lua" })
      f:key("g")
      f:key("h")
      f:key("/")
      f:paste(".lua")
      f:key("<CR>")
      f:check(function()
        contains(f:text("Files"), "▾ src/deep")
        contains(f:at("Files"), "b.lua")
      end)
      f:key("g")
      f:key(toggle)
      f:check(function()
        contains(f:at("Files"), "▾ src/deep")
        contains(f:text("Files"), "b.lua")
      end)
      f:key("<Esc>")
      f:check(function()
        contains(f:text("Files"), "▸ src")
        assert(not f:text("Files"):find("a.txt", 1, true))
        assert(not f:text("Files"):find("b.lua", 1, true))
        eq(f.jobs, 3)
      end)
      f:key("q")
      f:run()
    end)
  end

  test("clearing search while typing restores saved folds", function()
    local f = fixture({ "src/a.lua", "src/deep/b.lua" })
    f:key("g")
    f:key("h")
    f:key("/")
    f:paste(".lua")
    f:check(function()
      contains(f:text("Files"), "a.lua")
      contains(f:text("Files"), "b.lua")
    end)
    f:key("<C-u>")
    f:check(function()
      contains(f:text("Files"), "▸ src")
      assert(not f:text("Files"):find("a.lua", 1, true))
      assert(not f:text("Files"):find("b.lua", 1, true))
    end)
    f:key("<CR>")
    f:key("q")
    f:run()
  end)

  test("refresh reapplies retained query, rebuilds index and preserves source line", function()
    local f = fixture({ "a.txt", "b.lua", "c.lua" }, { ["b.lua"] = "one\ntwo\nthree", ["c.lua"] = "old" })
    f:key("/")
    f:paste(".lua")
    f:key("<CR>")
    f:key("g")
    f:key("<CR>")
    f:key("j")
    f:key("1")
    f:check(function()
      f.paths = { "b.lua", "new.lua", "z.txt" }
      f.sources["b.lua"] = "one\nupdated two\nthree"
    end)
    f:key("r")
    f:check(function()
      contains(f:at("Files"), "b.lua")
      contains(f:at("Source"), "updated two")
      contains(f:text("Files"), "new.lua")
      assert(not f:text("Files"):find("c.lua", 1, true))
      assert(not f:text("Files"):find("z.txt", 1, true))
      eq(f.jobs, 6)
      f.paths = { "new.lua", "z.txt" }
    end)
    f:key("r")
    f:check(function()
      contains(f:at("Files"), "new.lua")
      contains(f:text("Source"), "new.lua")
      eq(f.jobs, 9)
      f.paths = { "z.txt" }
    end)
    f:key("r")
    f:check(function()
      eq(f:text("Files"), "No files")
      contains(f:text("Source"), "Select a file")
    end)
    f:key("<Esc>")
    f:check(function()
      contains(f:text("Files"), "z.txt")
    end)
    f:key("q")
    f:run()
  end)

  test("filename search handles an empty workspace and failed refresh", function()
    local f = fixture({})
    f:key("/")
    f:paste(".lua")
    f:key("<CR>")
    f:check(function()
      eq(f:text("Files"), "No files")
      contains(f:text("Source"), "Select a file")
      f.paths = { "new.lua", "other.txt" }
    end)
    f:key("r")
    f:check(function()
      contains(f:text("Files"), "new.lua")
      assert(not f:text("Files"):find("other.txt", 1, true))
      f.git_error = "listing failed"
    end)
    f:key("r")
    f:check(function()
      contains(f:text("Files"), "new.lua")
      assert(not f:text("Files"):find("other.txt", 1, true))
      contains(f.flashes[#f.flashes], "listing failed")
    end)
    f:key("q")
    f:run()
  end)

  test("retained search leaves Source refresh and editing independent", function()
    local f = fixture({ "a.lua", "b.lua" }, { ["a.lua"] = "one\ntwo", ["b.lua"] = "other" })
    f:key("<CR>")
    f:key("j")
    comment(f, "jump")
    f:key("1")
    f:key("/")
    f:paste("b.lua")
    f:key("<CR>")
    f:key("2")
    f:key("<CR>")
    f:check(function()
      f.sources["a.lua"] = "one\nrefreshed two"
    end)
    f:key("r")
    f:check(function()
      contains(f:at("Source"), "refreshed two")
      contains(f:at("Files"), "b.lua")
    end)
    f:key("e")
    f:check(function()
      eq(f.editor_paths[1], "/project/a.lua")
      contains(f:at("Source"), "refreshed two")
      assert(not f:text("Files"):find("a.lua", 1, true))
    end)
    f:key("q")
    f:run()
  end)
end
